version: "3.5"

services:
  # Postgre Database
  postgres:
    container_name: weather-database
    image: postgres
    environment:
      POSTGRES_USER: weatheruser
      POSTGRES_PASSWORD: weatherpassword
      POSTGRES_DB: weather
      PGDATA: /data/postgres

    volumes:
      - pg-weather:/data/postgres
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    ports:
      - "5436:5432"
    restart: unless-stopped
    # Backend

volumes:
  pg-weather:
